"""add_workout_log_status_and_time_fields

Revision ID: c6b6ccc87c49
Revises: 77b4e0013bd0
Create Date: 2025-01-15 10:45:08.713230

"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6b6ccc87c49'
down_revision: Union[str, None] = '77b4e0013bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First add nullable columns
    op.add_column('workout_logs', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_logs', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_logs', sa.Column('status', sa.String(), nullable=True))

    # Update existing records
    op.execute("""
        UPDATE workout_logs 
        SET start_time = created_at,
            end_time = created_at,
            status = 'completed'
    """)

    # Now make columns non-nullable
    op.alter_column('workout_logs', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('workout_logs', 'status',
               existing_type=sa.String(),
               nullable=False,
               server_default='completed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'status')
    op.drop_column('workout_logs', 'end_time')
    op.drop_column('workout_logs', 'start_time')
    # ### end Alembic commands ###
